- cxx/include/mspass/utility/Metadata.h
- cxx/python/mspass_wrapper.cpp
- cxx/src/lib/utility/Metadata.cc
- python/mspasspy/mongodb/history.py
Have a look at this and see if you think this is an appropriate initial solution for processing history preservation.   I'm going to expand the concepts in the issues section on this topic, but look here for the implementation.
> Cxx add historychaining

- cxx/include/mspass/algorithms/algorithms.h
- cxx/include/mspass/utility/Metadata.h
- cxx/python/seismic/seismic_py.cc
- python/mspasspy/db.py
- python/mspasspy/io/converter.py
- python/mspasspy/preprocessing/css30/dbarrival.py
- python/mspasspy/preprocessing/css30/dbexport_to_mongodb.csh
- python/mspasspy/preprocessing/seed/ensembles.py
- python/mspasspy/util/Undertaker.py
Some of this stuff is a bit rough, but can at least serve as the basis for discussion on the database api.  I think it is a point of discussion as to what should be done before it is assimilated into master, but important to get it here so you guys can review what I've done.
Note there is an important additional element of this branch. I added a new raw_data_tutorial to the notebooks section.  The notebook should work with the new preprocessing libraries in this branch.   To use the tutorials you will need to pull this branch, build it, and then pull the tutorial and run it.
> Raw data handling

- cxx/src/lib/algorithms/bundle.cc
This branch resolved the divergence issue in #119.
> Fix bundle2

- cxx/include/mspass/seismic/Ensemble.h
- cxx/python/seismic/seismic_py.cc
- data/yaml/mspass.yaml
- python/mspasspy/db/database.py
- python/mspasspy/db/schema.py
- python/tests/db/test_db.py
- python/tests/db/test_schema.py
- python/tests/test_ccore.py
This is to address various issues discussed in https://github.com/wangyinz/mspass/discussions/122
> Fix issues of database behavior

- python/mspasspy/preprocessing/css30/dbarrival.py
- python/mspasspy/preprocessing/seed/util.py
These are the changes I made to the preprocessing modules in building the full usarray metadata set for the planned publication.   They should merge clean as I don't think anyone else was working on this set of files.
> Add seed util

- data/yaml/mspass_lite.yaml
- python/mspasspy/db/database.py
- python/mspasspy/db/schema.py
- python/tests/db/test_db.py
- python/tests/db/test_schema.py
This is to address issues discussed in #136.
> Revise schema definitions

- .gitignore
- python/mspasspy/db/schema.py
* use schema library to create a custom schema template for check
> Implement check_format for schema

- docs/source/conf.py
- docs/source/cxx_api/index.rst
- docs/source/cxx_api/mspass.Metadata.rst
- docs/source/cxx_api/mspass.Seismogram.rst
- docs/source/cxx_api/mspass.TimeSeries.rst
- docs/source/cxx_api/mspass.seismic.Seismogram.rst
- docs/source/cxx_api/mspass.seismic.TimeSeries.rst
- docs/source/cxx_api/mspass.utility.Metadata.rst
- docs/source/user_manual.rst
- docs/source/user_manual/CRUD_operations.rst
- docs/source/user_manual/adapting_algorithms.rst
- docs/source/user_manual/data_object_design_concepts.rst
- docs/source/user_manual/database_concepts.rst
- docs/source/user_manual/processing_history_concepts.rst
- docs/source/user_manual/time_standard_constraints.rst
I pushed this because the new document on CRUD operations includes a lot of prototype suggests on how the database api should behave.  It is mostly up to date with things on the discussion pages and in the google design doc.   I would hope it provides a new summary of how we currently think it should behave.   Suggest you merge it to master as there shouldn't be any conflicts.  Well, there might be some conflicts with documentation in a previous pull request that hasn't yet been merged with master.  Followed the directive we decided last Thursday to when in doubt add a new branch from the most current master.
> New documentation pages and edits to existing

- .github/workflows/python-package.yml
- docs/requirements.txt
- docs/source/conf.py
- python/mspasspy/db/database.py
- python/tests/db/test_db.py
bugfix for ignore_metadata_changed_test in save_data
> fix update_metadata bug for ignore_metadata_changed_test

- docs/source/user_manual/CRUD_operations.rst
- docs/source/user_manual/data_object_design_concepts.rst
- docs/source/user_manual/introduction.rst
This branch should be trivial to merge.  Just has revisions to three pages in the user manual  - three rst files.  Should not impact any of the code base.   Synced with origin/master about 5 minutes before the new files were copied to this branch.
> Edits to user manual to hadle some recent api changes

- python/mspasspy/db/database.py
- python/tests/db/test_db.py
bugfix for print_ message initialization problem. #209
> bugfix for initialization problem

- scripts/start-mspass.sh
- scripts/tacc_examples/distributed_node.sh
- scripts/tacc_examples/single_node.sh
These are some changes I made in start-mspass.sh script, but there might be more changes on them.
> bugfix for minor issues in start-mspass.sh script

- python/mspasspy/algorithms/RFdeconProcessor.py
bugfix for TimeWindow import error
> bugfix for import error

- scripts/start-mspass.sh
- scripts/tacc_examples/SAGE_2021_script.sh
> SAGE 2021 job script update

- .github/workflows/code-format.yml
use black and suggester to format python files when changed.
> CI: python formatter

- Dockerfile
- Dockerfile_dev
- python/mspasspy/algorithms/RFdeconProcessor.py
- python/mspasspy/global_history/ParameterGTree.py
- python/mspasspy/global_history/manager.py
- python/mspasspy/util/converter.py
- python/tests/algorithms/test_RFdeconProcessor.py
- python/tests/global_history/test_gtree.py
- python/tests/global_history/test_manager.py
- python/tests/helper.py
Add AntelopePf2dict to convert pf object to dict,
Add ParameterGTree to store parameters,
Integrate ParameterGTree into GlobalHistoryManager.
> Parameter definitions

- python/mspasspy/db/database.py
- python/tests/db/test_db.py
This is the bugfix for issue #261 
Basically, we use the obspy built-in merge function to fix this.
> bugfix for the mseed gaps

- python/tests/db/test_db.py
- requirements.txt
fix the bug in the test for the mseed gap issue.
> Bugfix mseed gaps test

- python/mspasspy/db/normalize.py
- python/tests/db/test_normalize.py
This PR contains the clean change to fix the bug discussed in #315
> Normalize bugfix2

- cxx/src/lib/seismic/CoreSeismogram.cc
- cxx/src/lib/seismic/TimeSeries.cc
- python/tests/test_ccore.py
> Npts md bugfix2

- python/mspasspy/db/normalize.py
- python/tests/db/test_normalize.py
This branch fix the bug discussed in #321
> fix single_key_matcher

- python/mspasspy/db/normalize.py
- python/tests/db/test_normalize.py
> add optional time_key to init

- .github/workflows/python-package.yml
- docs/requirements.txt
- docs/source/conf.py
- python/mspasspy/algorithms/basic.py
- python/tests/algorithms/test_basic.py
- python/tests/algorithms/test_signals.py
For issue #332 Problem with ExtractComponent
> Add Extract Component Function and Tests

- docs/source/index.rst
- docs/source/user_manual/normalization.rst
This only adds an rst documnt on normalization.   You guys should probably read it and we need to check if the sphynx stuff worked correctly before we merge it, but there should not be any other conflicts as it is a tiny increment from master.
> New normalize documentation

- .github/workflows/code-format.yml
- .github/workflows/docker-publish.yml
- docs/source/conf.py
- docs/source/mspass_schema/build_metadata_tbls.py
- setup.py
This is to remove the use of reviewdog in current workflow that could easily overflows the comments in a PR.
> Test for code formatting as PR

- cxx/src/lib/algorithms/slice_and_dice.cc
There was a pending pull request that had been sitting for almost a year called "improve_window" that I just deleted.  This is a replacement for that pull request.  The reason the other was never done was it had improperly mixed in some python code for the normalize module which caused all kinds of conflicts in a simple merge.  The normalize module was stabilized some time ago so all I did was pull some changes in the C++ code for windowing to this new branch.   I expect all the texts here should come up clean as the only changes in in one C++ file that should not break anything.
As a reminder the fix here was purely an efficiency change.   The previous code called the copy constructor before windowing data.   That caused unnecessary memory bloat when cutting up very long files like day …
> Improve Window - cleaned up

- python/mspasspy/db/database.py
- python/mspasspy/io/distributed.py
- python/tests/io/test_distributed.py
Set objects alive and load history in `read_to_dataframe` method
> fix no history in new io module

- .github/workflows/python-package.yml
- cxx/cmake/pybind11-download.cmake
- docs/source/user_manual/CRUD_operations.rst
- python/mspasspy/db/database.py
- python/tests/db/test_db_spark_dask.py
Updated doc and added check for file format in `read_ensemble_data_group()`. The new function can only read from binary files. #409
> added doc and warning for read_ensemble_data_group()

- scripts/start-mspass.sh
For #423, The `mongo` shell is removed from MongoDB 6.0. The replacement is 
[`mongosh`](https://www.mongodb.com/docs/mongodb-shell/#mongodb-binary-bin.mongosh)
> update mongo command to mongosh in mongo 6.0

- README.md
Update our home page per discussions in https://github.com/mspass-team/mspass/discussions/465
> Update README.md with a pointer for contribution guides.

- python/mspasspy/db/database.py
- python/mspasspy/io/distributed.py
This fix should correct the bug I was chasing yesterday that caused me to start the discussion topic #493.   The previous version was not handling dead data correctly and was failing when the database routine _save_sample_data was referencing a null matrix write_distributed_data was creating due to a mistake in the logic of handling dead data.  
I tested most of this code by hacking the container and resolving the problem with the parallel workflow.  I did not change the test script for distributed.py to test this condition.   We should do that later.  To get this fixed I plan to verify it recreates the successful run on a part of the 2012 usarray data set using the volatile container this pull request will create.  I'll leave a note in this pull request when I've verified that.  Before …
> bug fix for write_distributed_data

- python/mspasspy/util/Undertaker.py
- python/tests/util/test_undertaker.py
Added a pytest script to test the Undertaker class (added in #472 )
> Add tests for new undertaker class

- .github/workflows/conda-build.yml
- meta.yaml
Use the conda_action branch to test conda in GitHub actions
> Conda action branch

- docs/source/getting_started/quick_start.rst
I noticed I missed one of the new pages for the documentation updates.   There should be no conflicts with this as it just adds one rst file
> Add missing file in major update

- python/mspasspy/db/normalize.py
- python/tests/db/test_normalize.py
Fixes a couple bad bugs in OriginTimeMatcher.   If this passes tests as it should it should be merged immediately.
> Fix several bugs in OriginTimeMatcher

- cxx/src/lib/algorithms/slice_and_dice.cc
- python/mspasspy/algorithms/window.py
- python/mspasspy/db/client.py
- python/tests/algorithms/test_window.py
This set of changes implements suggestions proposed in issue #551.   This also required very large changes to the pytest file for the WindowData function.   I think the revisions are pretty complete, but we should review the coverage data before this is merged.   It passed pytest locally so hopefully the only holdup may be in any missed coverage.
> Extend window data

- .github/workflows/python-package.yml
- Dockerfile
- pyproject.toml
- python/mspasspy/algorithms/ml/arrival.py
- python/tests/algorithms/ml/test_arrival.py
- requirements.txt
- setup.py
- This change implements a P wave arrival-time pick function based on the probability prediction from machine learning model.
- It leverages the SeisBench PhaseNet model for the probability prediction. 
- A probability threshold is used to choose picks.
- Time window is supported for focusing on a certain period of the input.
- unit test added for inputs that include mseed file, and trace object obtained using obspy.clients.fdsn.Client
> initial commit for adding the p wave pick function

- scripts/start-mspass.sh
update start-mspass.sh to fix memory issue
> update start-mspass.sh to fix memory issue
