.travis.yml, Dockerfile, cxx/CMakeLists.txt, cxx/cmake/boost-download.cmake, cxx/cmake/boost.cmake, cxx/include/mspass/seismic/BasicTimeSeries.h, cxx/include/mspass/seismic/CoreSeismogram.h, cxx/include/mspass/seismic/Seismogram.h, cxx/include/mspass/seismic/TimeSeries.h, cxx/include/mspass/utility/ErrorLogger.h, cxx/include/mspass/utility/Metadata.h, cxx/include/mspass/utility/MsPASSCoreTS.h, cxx/include/mspass/utility/dmatrix.h, cxx/python/CMakeLists.txt, cxx/python/mspass_wrapper.cpp, cxx/src/lib/seismic/CoreTimeSeries.cc, cxx/src/lib/seismic/Seismogram.cc, cxx/src/lib/seismic/TimeSeries.cc, cxx/src/lib/utility/Metadata.cc, cxx/test/md/CMakeLists.txt, cxx/test/md/test_md.cc
Ian, I think this branch is now ready to merge.   pickle is working now for both Seismogram and TimeSeries objects with the caveats you will see in the issues section on serialization issues.  
Here is a little test script you can use to validate this - you will need to modify the sys.append.path as I'm using that approach right now for handling the ccore library.  Also you may need to set LD_LIBRARY_PATH to the location of boost libraries.    Here is the script:
```
import sys
sys.path.append('/home/pavlis/src/mspass/python')
from mspasspy.ccore import CoreSeismogram
d=CoreSeismogram(200)
d.put_double('delta',1.0)
d.put_double('dt',1.0)
d.put('npts',200)
d.ns=200
d.t0=100.0
d.live=True
from mspasspy.ccore import Seismogram
d2=Seismogram(d,'invalid')
import pickle
x=pickle.dumps(d2) …
```
=> Pickle ccore

python/mspasspy/graphics.py
I think this code is ready to be considered for assimilation into the master branch.   I implemented two different plotting objects with the same user API:  (1) SectionPlotter makes seismic reflection style plots and (2) SeismicPlotter makes plots in the normal seismology convention (time as the x axis).   These should be viewed as base classes for more advanced graphics that should be feasible through the maplotlib.pyplot engine.  
Note that although SectionPlotter and SeismicPlotter have the same public API, they are implemented quite differently.   SectionPlotter was built by (quite extensive) modification of the plotting code I found in the 
(apparently depricated) code from fatiando a terra.   SeismicPlotter has some efficiencies for handling 
irregular sample rate data that …
=> Add graphics

cxx/include/mspass/algorithms/deconvolution/CNR3CDecon.h, cxx/include/mspass/algorithms/deconvolution/WaterLevelDecon.h, cxx/include/mspass/seismic/CoreSeismogram.h, cxx/include/mspass/seismic/CoreTimeSeries.h, cxx/include/mspass/seismic/Seismogram.h, cxx/include/mspass/seismic/TimeSeries.h, cxx/python/algorithms/deconvolution_py.cc, cxx/python/seismic/seismic_py.cc, cxx/python/utility/utility_py.cc, cxx/src/lib/algorithms/deconvolution/CNR3CDecon.cc, cxx/src/lib/seismic/CoreSeismogram.cc, cxx/src/lib/seismic/CoreTimeSeries.cc, cxx/src/lib/seismic/Seismogram.cc, cxx/test/tcs/test_tcs.cc, cxx/test/tcs/test_tcs.out, python/mspasspy/algorithms/RFdeconProcessor.py, python/mspasspy/db/database.py, python/mspasspy/util/converter.py, python/tests/algorithms/test_window.py, python/tests/db/test_db.py, python/tests/db/test_schema.py, python/tests/test_ccore.py, python/tests/test_find_channel.py
This has some bug fixes to deconvolution processors I found while writing a first draft for a deconvolution tutorial.  The changes to CNR3CDecon are fairly significant to make it more robust.   There is a critical change the pybind11 code to fix a problem with std::vector binding noted for the record on [this issues page.](https://github.com/wangyinz/mspass/issues/96).
This also contains some important fixes to the Seismogram and TimeSeries APIs.  I had forgotten they where inside this.
Also checked in the new deconvolution tutorial so I recommend running that jupyter notebook tutorial when this is installed.
=> Decon repairs

python/mspasspy/db/database.py, python/tests/db/test_db.py
This commit fixes the logic that the inserted id of the history object should be the UUID set in the processing history class.
Since deep-copy in testing will copy the same UUID and result in mongo duplicate-key-error, modifications are made, i.e. using logging_helper to create a new node.
=> fix history object id type && testing

python/mspasspy/preprocessing/seed/ensembles.py
This branch has three changes.  Two I doubt you will have problems with but item 3 below will require a decision from on how to handle it.  First, here are the things changed:
1.  In finalizing the raw data tutorial, which is a prototype for our benchmark workflow the the usarray data, I fixed a couple of minor bugs in the ensemble.py file.  
2. As an aid to sorting out some additional site and channel metadata problems I developed two functions I think are useful additions to the database api.  These functions are called *site_report* and *channel_report*.  The produce a nicely formatted display of key metadata for a selected equal match to one or more of the keys net, sta, chan, loc.  I put them in the database.py module because I thought they belonged there.  I do not, however, think …
=> Improve preprocessing

python/mspasspy/db/database.py, python/tests/data/TA.035A.xml, python/tests/db/test_db.py
This is a simple change to the current database.py file that was split from master only about 2 hours ago.  The only changes are the addition of a new get_response method to Database.  There are complete docstrings but this method is needed to complete a tutorial handling response data for MsPASS - there is presently only a skeleton in the tutorial repository. 
This small test program is how I tested this.  I does not mesh with the automated test setup in this repository, but I'll leave that to someone else.   This little program can be run after completion of the getting started tutorial.  The idea is a user could run the response tutorial after getting started and run a variant of this little program in jupyter.  Anyway, here it is if you want to try it - noting you will at least need …
=> Add get_response method for Database class

docs/source/user_manual.rst, docs/source/user_manual/handling_errors.rst, docs/source/user_manual/introduction.rst
The only changes in this branch from the origin pulled only moments ago is the addition of two new rst documents in source:  an introduction document and a section on error handling.  I did not edit the index html as I'm not sure how that is handled in the sphynx setup.  This should merge clean.  The rst file previews fine for me.  Only question is if you need some special formatting commands to mesh with sphynx.
=> Add two new documentation pages

cxx/include/mspass/seismic/keywords.h, cxx/python/seismic/seismic_py.cc
This is a trivial fixed in the c++ code for mistake in the name for souce depth.  Was incorrectly tagged as SEISMICMD_selev and set as source_selev.  Changed selev to sdepth.  
Only complication is watch the history.  I incorrectly forgot to switch the branch name and originally committed these to master.  To allow me to push it to github I did
```
git checkout fix_keyword_bug
git merge master
```
then pushed it here.   Not sure if that will mess up the history chain or not.
=> Fix incorrectly named keyword

cxx/src/lib/CMakeLists.txt, cxx/src/lib/algorithms/CMakeLists.txt, cxx/src/lib/algorithms/deconvolution/CMakeLists.txt, cxx/src/lib/seismic/CMakeLists.txt, cxx/src/lib/utility/CMakeLists.txt
The cxx code should be built into a single library to avoid confusion. We switched the static libraries to object libraries in cmake to maintain the original build structure.
=> Revise CMake config

docs/source/man/man1/dbverify.1, python/mspasspy/db/editing.py, python/mspasspy/db/script/dbclean, python/mspasspy/db/script/dbverify, python/mspasspy/db/verify.py
These changes should be completely orthogonal to anything else in the repository.   There are some thing that will need further action though:
1.  I put the command line tool (python program with a main) dbverify in mspasspy.db.scripts as you suggested.   I have no idea how to change setup to have it installed in some kind of bin directory.   I leave that to one of my fellow collaborators. 
2. I wrote the man page in old school classic unix nroff with the -man dialect - the standard language for unix man pages for close to 40 years.  If you want it in a different structure, there are likely converters because man pages are everywhere.  I created a docs/source/man/man1 directory and put the file there.
=> Add new dbverify command line tool and related python module verify

cxx/include/mspass/utility/Metadata.h, cxx/python/seismic/seismic_py.cc, cxx/python/utility/utility_py.cc, cxx/src/lib/utility/Metadata.cc, cxx/test/md/test_md.cc, python/tests/test_ccore.py
This is an attempt to fix #173, the serialization problem in `Metadata`.  Because we previously rely on parsing its contents into strings, an empty string can confuse the parser when deserializing. The fix is simple but not necessarily efficient: convert the `Metadata` to `dict` and then pickle it. The previously ignored `changed_or_set` member variable is also properly serialized in this version.
=> Fix empty string issue in serializing Metadata

python/mspasspy/db/database.py, python/tests/db/test_db.py
fix the reader that converts the attribute to the correct type. It should overwrite the attribute value of the key in the metadata we have built.
=> bug fixed for reader

python/mspasspy/db/database.py, python/tests/db/test_db.py
When trying to save/update a mspass_object, if we could not find the wf record in the database according to the _id field associated with the mspass_object. We should either continue to save the metadata or raise an error. The rules are:
1. If we only update the mspass_object, we could continue to update only if it is under promiscuous mode
2. If we gonna save the mspass_object, we would treat it as insertion and remove its _id field. Semantically, when we want to save mspass_object with a meaningless _id field, we focus on the metadata associated with the object, thus we could treat it as an insertion.
=> bugfix for update metadata

docs/source/getting_started/run_mspass_with_docker.rst
As I understand it, DockerHub account is not required to use Docker and MsPASS. The following sentence may give users wrong impression that a docker hub account is necessary. I think it should be removed from the "Get Started" section to lower the barrier for new users.
> You may want to create an account and sign in your Docker following this instruction.
=> Remove the sentence about DockerHub account

docs/source/conf.py
Currently, each page on the documentation shows a "View page source" link, which links to the plain text source file:
It's more useful to link directly to the source files in the GitHub repository, because the source files are rendered well on GitHub and are easier to read. It's also much easier for users to submit quick fixes for typos.
The `html_context` is documented in https://github.com/readthedocs/sphinx_rtd_theme/issues/465.
It works well in my other projects, so I expect it should work well for mspass too. However, I can't test it because for me, it's difficult to build mspass from source codes locally.
=> Add configurations to show the 'Edit on GitHub' button

cxx/python/seismic/seismic_py.cc, data/yaml/mspass.yaml, data/yaml/mspass_lite.yaml, python/mspasspy/db/database.py, python/tests/db/test_db.py, python/tests/db/test_schema.py, python/tests/helper.py, python/tests/test_ccore.py
1. fix bugs for not saving tmatrix and two boolean variables properly in metadata before actually saving to database
2. For the constructor in TimeSeires, I remove the for loop and change it for memcpy for better performance
3. convert the cursor to a list to fix bugs for getting the length of the records correctly when passing MongoDB cursor in read_ensemble_data
4. update the format of yaml files to support the new features.
=> Bugfix db ensemble data

cxx/src/lib/algorithms/bundle.cc, cxx/src/lib/seismic/CoreSeismogram.cc, data/yaml/mspass.yaml, data/yaml/mspass_lite.yaml, python/mspasspy/algorithms/bundle.py, python/mspasspy/db/database.py, python/tests/db/test_db.py, python/tests/global_history/test_manager.py
This branch has a complete rewrite of the save_data method and update_metadata method.  It removes the private _update_metadata method completely.   save_data now is the union of the old _update_metadata and the old save data.   The new update_metadata method behaves very differently from the old one.   See doctrings for details. 
This first push is known to be broken.   I am getting weird results locally with pytest that i am pretty sure are related to the fact my development ubuntu machine has an incomplete test environment.   This push should not be taken seriously until I can view the test run results and try to fix what I can.   @haruming  I will need your help resolving some of the test conflicts and revising the test script to mesh with the changes to save_data and update_metadata.
=> Fix readonly problem

cxx/python/seismic/seismic_py.cc, cxx/src/lib/utility/AntelopePf.cc, python/mspasspy/algorithms/RFdeconProcessor.py, python/tests/algorithms/test_RFdeconProcessor.py
We run into the error that RFdeconProcessor was not able to be serialized by pickle automatically when using it in a map call. This is because a lot of the member variables of this python object are C++ bonded objects. Therefore, we are will not be able to use the object at all unless we serialize all the related C++ objects with pybind11. This includes the different decon operators as well as other underlying objects such as `ComplexArray` and `ShapingWavelet`. 
Therefore, instead of implementing the pickle method of all those objects, I decided to change the `RFdeconProcessor` python object such that it does not store copies of the actual decon processor. Instead, it creates one on the fly with all the necessary parameters stored in it that are native to Python. The overhead of this …
=> Change the structure of the RFdeconProcessor to make it serializable

data/yaml/mspass.yaml, data/yaml/mspass_lite.yaml
This is a change only to mspass.yaml to fix an unambiguous mistake in mspass schema.  I found this by running clean_collection in the short course tutorial and found it cleared data_tag I had set in the save.  I wasn't sure if that attribute should be tagged "normal" or "optional".   I set it "normal", but am a bit fuzzy on the distinction
=> Add missing information for data_tag

cxx/python/algorithms/basic_py.cc, cxx/python/seismic/seismic_py.cc, cxx/python/utility/utility_py.cc, python/mspasspy/algorithms/basic.py, python/tests/algorithms/test_basic.py, python/tests/test_ccore.py
While working out the parallel workflow for the tutorial, we found that the taper functions also needs to be serializable. This branch includes the following changes:
- added wrapper function for tapers
- added basic algorithmic methods for the `DoubleVector` object and it now behaves more close to a numpy array
- made SphericalCoordinate and SlownessVector serializable as they can be used as arguments in a map call to certain algorithms
=> Add taper functions

python/mspasspy/util/decorators.py, python/tests/algorithms/test_basic.py
bugfix for decorators:
when there is an error when running the try block in the mspass_func_wrapper and inplace_return is True, we better return the original data object so that it won't block the downstream processing.
=> bigfix for decorator error handling

python/mspasspy/db/database.py, python/tests/db/test_db.py
This is a small fix to handle a different bug in read_ensemble than the one discussed [here](https://github.com/mspass-team/mspass/issues/262).  Some time ago we extended Ensembles to add an error log and a feature wherein an entire ensemble can be killed (set dead).   The problem this bug fixes is ensembles read from MongoDB are always left with the state marked dead.   This probably didn't surface before because we didn't have a test workflow that properly tested that condition.  
This fix is pretty simple and only consists of a handful of additional lines of code.  One thing that might be open to discussion is how I did handled the inverse - saving an ensemble.  I added code that if the ensemble is marked dead save_ensemble does nothing.
=> Fix bug in failing to handle added live/dead feature

python/mspasspy/db/database.py, python/tests/db/test_db.py
This is the bug fix for issue #262.
Basically, we ignore reading the attributes if they are not in the normalized records. However, if they are required attributes, we post an elog entry to the wf object that is created after.
=> bugfix for the reader in missing attributes

cxx/include/mspass/seismic/SlownessVector.h, cxx/python/seismic/seismic_py.cc
This is a fairly trivial repair to fix two issues I found with SlownessVector:
1.  The API has a necessary parameter for setting the azimuth the object returns if a vector has zero length.  Otherwise one would get a NaN.  The fully parameterized constructor allows changing that but the C++ include has a default of the azimuth0 value to 0.  A C++ default does not port to python directly in any way.  I added a simple, but obscure change to the pybind11 definition of that constructor to give use keyword arguments with default values.  The syntax is very weird and serves as a useful example I hadn't seen before. 
2. I added boost serializiation code for SlownessVector to the include file.  Not essential for the python code, but a necessary evil for pwmig where I need to serialize a …
=> Improve slowness vector

python/mspasspy/algorithms/window.py
This fixes a bug in WindowData that did not handle the t0shift options correctly.  It failed every time it was called because the range test used did not apply the shift when that was enabled.  The changes are pretty trivial so I advise you simply merge this branch immediately. 
Longer term action is needed to have the tests check the t0shift option.  This bug was present because that test was missing.   I looked at the test code and decided it was not so trivial to fix because the existing test code is not set up for utc data where this feature would be used.   Advise you accept this pull request and post adding such a test to the fairly short term development agenda.
=> Fix bug when t0shift options is used

cxx/src/lib/seismic/CoreSeismogram.cc
I would suggest you do a quick review for anything obvious and merge this branch with master.  It contains only two minor things:
1. Fixed a bug in the CoreSeismogram constructor from a vector of CoreTimeSeries objects.  The previous version did not call set_live() on success so all data passed through it were marked dead.
2. I cleaned up a minor irregularity in handling dead dead for operator+= and unncessary relic code dealing with a const issue that is no longer relevant.
=> Minor bug fix

python/mspasspy/db/database.py, python/tests/db/test_db.py
This PR fix the bug in #333, where a killed object during the file reading is set back to alive later by mistake
=> Fix bug wrongly setting object alive in read_data

cxx/python/algorithms/basic_py.cc, python/mspasspy/algorithms/RFdeconProcessor.py, python/mspasspy/algorithms/basic.py, python/mspasspy/algorithms/snr.py, python/mspasspy/graphics.py, python/mspasspy/util/converter.py, python/tests/test_ccore.py
For residual problem with graphics module #343 , I changed all EnsembleComponent to ExtractComponent. But the graphics tutorial still cannot work.
Because in `ExtractComponent()`, I added a conditional statement `if data.dead():`, to ensure the input data is live. If the data is dead, `ExtractComponent()` will return an empty object. In the graphics tutorial, `makeseisens()` function in graphicstutorial.py (line 114) generates a TimeSeries ensemble that is dead. So the graphics tutorial does not work.
```
def makeseisens(d,n=20,moveout=True,moveout_dt=0.05):
"""
Makes a TimeSeries ensemble as copies of d.  If moveout is true
applies a linear moveout to members using moveout_dt times
count of member in ensemble.
"""
result=SeismogramEnsemble()
for i in range(n):
y=Seismogram(d)  # this …
```
=> For residual problem with graphics module #343 

cxx/src/lib/algorithms/snr.cc, cxx/src/lib/seismic/CoreSeismogram.cc, python/mspasspy/algorithms/snr.py, python/mspasspy/db/normalize.py, python/tests/algorithms/test_snr.py
This should largely finish the snr module for now.   Includes a bunch of bug fixes found when applying this to thousands of real data from our large usarray test data set that is not feasible to put in github due to the size.  In the process I also reorganized the top level function to split what previously was a single function into two.   That is necessary to allow the user to run the same function either inline with a map call followed by filter to remove junk or in a database mode where the computed metrics are posted to an arrival collection.
This also now has a complete test suite for the functions in snr.py.   I'm sure coverage will show some missing but I think the tests cover the main features. 
Before this branch is merged we need to decide if we need to add a formal "arrival" …
=> Extend snr

python/mspasspy/db/collection.py, python/mspasspy/db/database.py, python/tests/db/test_collection.py
@pavlis has discovered a potential bug where calling any function that uses the Database class may run into the error saying:
```
TypeError: codec_options must be an instance of bson.codec_options.CodecOptions
```
The full error log from the run looks like this:
```
TypeError Traceback (most recent call last)
<ipython-input-24-dc62b940ab12> in <module>
43 cursor=db.wf_miniseed.find(query)
44 seisbag = read_distributed_data(db,cursor)
---> 45 seisbag.compute()
46 #seisbag = seisbag.map(detrend,type='constant')
47 #seisbag = seisbag.map(lambda d : ator(d,d[\"Ptime\"]))
/usr/local/lib/python3.6/dist-packages/dask/base.py in compute(self, **kwargs)
281 dask.base.compute
282 \"\"\"
--> 283 (result,) = compute(self, traverse=False, **kwargs)
284 return result
285 …
```
=> add customized collection class

cxx/src/lib/io/fileio.cc
This should fix the mistake that caused the last version to abort
=> Pavlis patch 7

.github/workflows/docker-publish.yml, Dockerfile, Dockerfile_dev
When running MongoDB on arm, there were flags to disable sse2 and avx2, because of ENV variables defined in dockerfile. 
Removed the ENV variables and only set it inside a RUN command. They should not be present in the resulting Docker image.
=> fix cflags, sse2 and avx2 when building numcodecs in arm

python/mspasspy/db/client.py, python/mspasspy/db/database.py, python/tests/db/test_client.py, python/tests/db/test_db_no_spark_dask.py
This PR fix the API for db client, in which get_database method can set the default schema. We also added a single call to change the default schema in the Database class
=> add schema option

cxx/python/seismic/seismic_py.cc, python/tests/test_ccore.py
This branch has a trivial change.  I added a one line lambda to the pybind11 code for BasicTimeSeries to add an alias "starttime" method that is effectively the same thing as the t0 method of BasicTimeSeries.   Python applications can use starttime() an alternative to using the attribute t0.  To some it might be less confusing since there is already and endtime() method.
=> add starttime method

docker-compose.yml, docs/source/getting_started/deploy_mspass_on_HPC.rst
1. Add a note in the HPC document to specify the hostname when running MsPASS on distributed nodes
2. Update `docker-compose.yml` from version 3 to 3.7 and grammar changes
=> Updated HPC doc and docker-compose.yml

cxx/src/lib/io/fileio.cc, python/tests/db/test_db_spark_dask.py
I found when running the code below, `index out of range` error occurs.
```python
db.save_ensemble_data_binary_file(e,dir=dir,dfile=dfile)
```
Reason:
In `fwrite_to_file` function, dead data is skipped and its foff is not added to the foffs array, so the array is shorter than the length of the ensemble. However, the `save_ensemble_data_binary_file` function thinks the foffs array has the same length of the ensemble, so the index is out of range.
My fix is also adding a foff(0) for the dead object, it will not be used but can prevent the index error.
=> fix array bug in fileio

data/yaml/mspass.yaml, data/yaml/mspass_fdsn.yaml, data/yaml/mspass_lite.yaml, data/yaml/mspass_s3.yaml, python/mspasspy/db/database.py, python/tests/db/test_database.py
=> Fix bug in handling starttime and endtime

python/mspasspy/db/database.py
This should resolve an issue I just posted with index_mseed_file not setting the "time_standard" attribute to "UTC".
=> fix time_standard bug in index_mseed_file

python/mspasspy/db/database.py, python/tests/test_mspass_client_spark_dask.py
I think this will fix the bug in reading ensembles from files.   I haven't run these through pytest yet so may require a second iteration to fix this.   This is a pretty serious bug as reading from miniseed files fails until this is fixed.
=> Fix bug in handling ensemble files with mixed storage mode

python/mspasspy/db/database.py
This is a bug that refuses to die.   Thought we had killed in months ago.   Adds "endtime" attribute to dict returned by this method.
=> bug fix to Database._convert_mseed_index

python/mspasspy/db/database.py
This fixes a bug created by an api mismatch between Metadata and dict.  Code used erase on a dict which throws an error when it is executed.
=> Bug fix handling data_tag

cxx/include/mspass/seismic/DataGap.h, cxx/include/mspass/seismic/TimeSeriesWGaps.h, cxx/python/seismic/seismic_py.cc, cxx/src/lib/seismic/DataGap.cc, python/tests/test_ccore.py
This started out as a simple bug fix for a mistake in the pybind11 code for this auxiliary class.   I realized, however, that in working with a prototype for surgical mutes that this was a very useful container that might work well as a component of a generic surgical mute algorithm.   Working on the prototype with a data set from Homestake I realized it lacked a couple important capabilities:
1.  The previous version required gaps intervals to not overlap.  An attempt to add a gap definition that overlapped an existing one would cause nothing to happen.   That happened because the original concept was recorded data gaps, which are effectively always immutable.   For a more generic use that needed to be relaxed.  I did that here by adding some minor complexity to the add_gaps method. …
=> Fix data gap

python/mspasspy/graphics.py
Two things in this set of changes:
1.  Fixed a long standing bug that messed up scaling of plots in the "wtvaimg" mode.    Fix may not be perfect, but is an improvement over present form that produces really bad plots in that mode most of the time.   The possible residual issue is that we may need to handle the "aspect" parameter for image plotting more elegantly.   I'm not sure with these changes a user can actually change the aspect ratio manually.   I don't expect that to be a very common need though so I didn't think the effort required to test all the possibilities was worth the trouble.
2. I changed the default style to "wtva" (wiggle trace variable area) instead of "wtvaimg" (the style that previously was giving trouble).   Maybe should be the simplest "wt" but in most cases wtva …
=> Fix graphics

cxx/src/lib/seismic/CoreSeismogram.cc, cxx/test/tcs/test_tcs.cc, python/mspasspy/algorithms/basic.py, python/tests/algorithms/test_basic.py, python/tests/test_ccore.py
Fixes and extensions to address Issue #511.   Five major changes/additions:
1.  Adds new transform_to_RTZ function
2. Adds new transform_to_LQT function
3. Changes the api for free_surface_transformation to add more flexible input.  Default now assumes fetching required data from Metadata to make the function easier to use in a map operator. 
4. Complete pytest functions for the above. 
5. Cleaned up a confusion on the sign of the angle of rotation for the overloaded C++ function.  That is now largely hidden behind the higher level functions anyway but the most important fix is making the sign convention unambiguous in the doxygen comments.
Note I'm pushing this to verify all the changes match my local test runs.    I want to do a final sanity check against data before suggesting this …
=> Extend 3c transforms

docs/source/user_manual/adapting_algorithms.rst, docs/source/user_manual/continuous_data.rst, docs/source/user_manual/data_object_design_concepts.rst, docs/source/user_manual/database_concepts.rst, docs/source/user_manual/graphics.rst, docs/source/user_manual/handling_errors.rst, docs/source/user_manual/header_math.rst, docs/source/user_manual/importing_tabular_data.rst, docs/source/user_manual/mongodb_and_mspass.rst, docs/source/user_manual/obspy_interface.rst, docs/source/user_manual/parallel_processing.rst
This is a pure documentation edit that should merge with zero issues.   The fixes are mostly format fixes for some improperly formatted sphynx link directives - hyperlinks and some internal python classes.  It also universally converts TimeSeries and Seismogram references to docstring links instead of just highlighting.   Also a few edits found while fixing the other stuff.  
I wasn't actually able to test these fixes because my local copy doesn't work right with docstring cross references.  This should be used anyway as it corrects some glaring errors
=> Edit user manual

.github/workflows/conda-build.yml
It seems GitHub now has arm runners when using macos-14. Testing it out here.
=> Add osc-arm64 build of conda using the new osx-14 runner

python/mspasspy/db/database.py, python/mspasspy/io/distributed.py
The distributed module will error out when either dask or pyspark is not installed. This strict dependency of two packages is not necessary. We need to handle the import with try clause instead.
=> Handles import with exception

python/mspasspy/client.py, python/mspasspy/db/database.py
hit this error in a run and realized it was just a typo - period should have been a comma.
BTW this suggests we need to run the equivalent of lint on our entire python code base.   I know there are such tools but I don't know what would be best to catch this type of usage error.   It wasn't caught because it wasn't a syntax error.   It might be impossible for current generation tools of that type to catch this particular type of typo.
=> fix typo in exception line

python/mspasspy/algorithms/resample.py, python/mspasspy/util/converter.py, python/tests/algorithms/test_resample.py, python/tests/util/test_converter.py
I fixed the issue of the attribute "sampling_rate" not updating when "dt" changes.
This happens in resample in resample.py and TimeSeries2Trace in converter.py.
I also edited the test code for the resample and it passed all the cases.
=> Fix "sampling_rate" not updating along with "dt"

python/mspasspy/algorithms/ml/arrival.py, python/mspasspy/algorithms/resample.py, python/mspasspy/algorithms/window.py, python/mspasspy/util/converter.py, python/tests/algorithms/ml/test_arrival.py, python/tests/algorithms/test_resample.py, python/tests/algorithms/test_window.py, python/tests/util/test_converter.py, setup.py
Based on new comments in [issue #545](https://github.com/mspass-team/mspass/issues/545), I removed the elog related to updating "sampling_rate" in resample.py.
=> Remove elog related to updating "sampling_rate" in resample.py

.github/workflows/python-package.yml, pyproject.toml, requirements.txt, setup.py
To make the `seisbench` dependency optional so that the size of the standard installment can be reduced.
Also need to update the container definition as part of this pr, so that dev container can have seisbench installed
Ran the following commands and verified seisbench is not installed in the first one
```
python3 -m pip install .
python3 -m pip install '.[seisbench]'
```
=> feat: make seisbench dependency optional 

cxx/include/mspass/algorithms/deconvolution/CNRDeconEngine.h, cxx/include/mspass/algorithms/deconvolution/FFTDeconOperator.h, cxx/include/mspass/algorithms/deconvolution/MultiTaperSpecDivDecon.h, cxx/include/mspass/algorithms/deconvolution/MultiTaperXcorDecon.h, cxx/python/algorithms/deconvolution_py.cc, cxx/src/lib/algorithms/deconvolution/CNRDeconEngine.cc, cxx/src/lib/algorithms/deconvolution/ComplexArray.cc, cxx/src/lib/algorithms/deconvolution/LeastSquareDecon.cc, cxx/src/lib/algorithms/deconvolution/MultiTaperSpecDivDecon.cc, cxx/src/lib/algorithms/deconvolution/MultiTaperXcorDecon.cc, cxx/src/lib/algorithms/deconvolution/ScalarDecon.cc, cxx/src/lib/algorithms/deconvolution/WaterLevelDecon.cc, python/tests/algorithms/test_CNRDeconEngine.py, python/tests/algorithms/test_RFdeconProcessor.py
As the name suggests this branch is a followup to the large commit that was merged just a few day ago to improve the deconvolution  modules.   The previous version had a known problem with serialization of the C++ classes.  This branch resolves that problem. 
The issue causing the serialization bug turned out to mostly be errors in the copy constructors for the C++ classes.  The serialization was working fine, but when pickle returned the copy the copy was flawed by having dropped critical data in the copy constructor called implicitly when the pybind11 code returned the pickle result to python.   
The tests for all of these operators could use some improvement but doing so will be difficult with static tests.   There are two issues:
1.  There could easily be unexpected runtime error …
=> Fix decon serialization

python/mspasspy/db/normalize.py, python/tests/db/test_normalize.py
In working with the extended usarray data set I discovered a gap in our implementation of the `OriginTimeMatcher` class.  I tried to run the `bulk_normalize` function on a database with around 3 million wf documents.   The aim was to produce a clean database with "channel_id" and "source_id" set so I could use id matching for processing this large data set.   It turned out `bulk_normalize` required `OriginTimeMatcher` to implement the "find_doc" method.    It did not have that previously. 
This revision removes the find_doc deficiency in `OriginTimeMatcher` but I went one step further.  That is, I realized that a generic version of `find_doc` was possible in the base cass `BasicMatcher`.   I implemented that.  However, I had to also create and override of the generic method in …
=> Improve OriginTimeMatcher

python/mspasspy/graphics.py
Adds a new superclass to SeismicPlotter to handle plotting large ensembles.  If one tries to plot more than a hundred or so signals at once you get a mysterious blank screen as all the plots are less than or near the size of one pixel.   To avoid that this superclass automatically plots ensembles in multiple windows.  
I also did some housecleaning on the SeismcPlotter class code.   
We do not have pytest functions for graphics.py but I did use this version to (a) run our basic graphics tutorial and (b) for debugging a timing issue on real data on the IU cluster.  It was very very helpful for the later.  I don't know how or if one could use pytest for a graphical module like this.
=> Add LargeEnsemblePlotter

cxx/include/mspass/algorithms/deconvolution/MTPowerSpectrumEngine.h, cxx/python/algorithms/deconvolution_py.cc
This fixes bug that causes mysterious behavior running broadband_snr_QC where it runs fine in serial but kills all inputs when run parallel.   There was an error in pybind11 code that used the default sample interval for a constructor used in the binding code.  Unless something unexpected happens in the github tests I suggest this be merged immediately.
=> Fix bug in serialization bindings for MTPowerSpectrumEngine

cxx/include/mspass/algorithms/amplitudes.h, cxx/src/lib/algorithms/deconvolution/MTPowerSpectrumEngine.cc, cxx/src/lib/algorithms/snr.cc, python/mspasspy/algorithms/snr.py, python/tests/algorithms/test_snr.py
This fixes a bug uncovered from processing a large data set.  Some situation I haven't unraveled sent a dead spectrum to a C++ function (repaired in this branch) that caused an unexpected exception to be thrown.   That caused an error handler in the snr.py module to be entered that had a mistake in usage.   The comments noted that the handler shouldn't be needed but was added for safety.  Maybe good it did have an error as it revealed the error in the C++ code.  
I did not add a pytest function for the error handler because it still is a handler that is there strictly as a safety valve.   I have no reason to think this pull request won't pass all tests so assuming that is true I urge you to merge it immediately.
=> bug fix for snr algorithms

docs/source/user_manual/algorithms.rst, python/mspasspy/algorithms/CNRDecon.py, python/mspasspy/algorithms/MCXcorStacking.py, python/mspasspy/algorithms/MTPowerSpectrumEngine.py, python/mspasspy/algorithms/RFdeconProcessor.py, python/mspasspy/algorithms/basic.py, python/mspasspy/algorithms/calib.py, python/mspasspy/algorithms/edit.py, python/mspasspy/algorithms/resample.py, python/mspasspy/algorithms/signals.py, python/mspasspy/algorithms/snr.py, python/mspasspy/algorithms/window.py, python/mspasspy/db/normalize.py, python/mspasspy/graphics.py, python/mspasspy/util/decorators.py, python/tests/algorithms/decon_data_generators.py, python/tests/algorithms/test_CNRDeconEngine.py, python/tests/algorithms/test_MCXcorStacking.py, python/tests/algorithms/test_RFdeconProcessor.py, python/tests/algorithms/test_basic.py, python/tests/algorithms/test_resample.py, python/tests/algorithms/test_taper.py, python/tests/algorithms/test_window.py, python/tests/util/test_decorators.py
This implements a change to the mspass decorators to make it easier to adapt an algorithm that works only on atomic data to ensembles.  It basically automates adding a loop over ensemble members.   It implements ideas documented in discussion item #616.  
The change required small changes to most of the code in mspasspy.algorithms to add a kwarg switch to tell the decorator to enable the ensemble loop.
This initial push is virtually guaranteed to fail the pytest run here on github.   I did not run pytest on all the algorithms and the odds are high I made a mistake or one of the test make an assumption that is invalid with the decorators enabled.   Also there will be a gap in the tests to verify the ensemble functionality works for algorithms not previously working that way.  The coverage …
=> Enhance decorators - discussion #616

python/mspasspy/db/database.py
This fixes a bug in the read_data method of Database.   The bug only happens if the reader is called with the data_tag argument set to a value.   The fix is one line that was botched.
=> Bug fix for read_data

python/mspasspy/db/database.py, python/mspasspy/db/normalize.py, python/tests/db/test_normalize.py
This branch contains a bug fix for two problems:
1.   I found the normalize function (in normalize module) did not work with ensembles because of a mistake I had made in application of the decorator extensions made recently.   
2. Issue #629 
In this initial push I haven't revised the test to check either of these fixes.  For 1 I'm not sure it is necessary as the only thing adding such a test would do was duplicate tests of the decorator and validate normalize does indeed work with ensembles correctly.  2 is more problematic as I am not sure how to do a test to check the error handlers I added.   The new handlers are there to handle corrupted or completely invalid data files.   I think just trying to read a junk file with content not matching the format would work, but I'm unsure how to …
=> normalize and database bug fixes

python/mspasspy/algorithms/window.py, python/mspasspy/db/normalize.py, python/tests/algorithms/test_window.py
This branch fixes three things:
1.   The normalize function does not currently use the mspass_func_decorator and will not work correctly with ensembles. 
2.   I fixed a couple of other mistakes in algorithms with functions that do are not handling *args and **kwargs correctly with the mspass_func_decorator.  It is VERY IMPORTANT to realize this fix is dependent that pull request #632 is a dead branch.   There I found the use of *args and **kwargs with these decorators is different from the stock way they are handled.  See the comments there for details.   I found additional evidence that #632 is the wrong approach as a fix here (next item) revealed exactly what happens when the #632 approach is used.
3. WindoData functions need to be corrected for use with mspass_func_decorartor.   I had …
=> bug fix for normalize and a couple other functions 
